baseURL = "http://bashthefash.ninja/"
languageCode = "en-us"
title = "BashTheFash"
theme = "btf"

[taxonomies]
  tag = "tags"

[params]
  about = "BashTheFash Mission Statement: To connect antifascists wherever they may be and facilitate organization and creation of local activist groups. Fascism NEEDS to met with equally hateful opposition. You're in the right place!"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "Sticker Requests"
    url = "/stickers/"
    weight = 3
  [[menu.main]]
    name = "History of Fascism"
    url = "/fascism/"
    weight = 4
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 5
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 6
